name: Deploy to server

on: push

jobs:
 first_job:
  runs-on: ubuntu-latest

  env:
   NAME: PedroGuaillas

  steps:
   - name: Hi world first
     run : echo "Hola mundo $NAME"
 
 seconds_job:
  if: ${{ github.ref == 'refs/heads/main' }}
  needs: first_job
  runs-on: ubuntu-latest

  steps:
   - name: Hi world seconds
     run : echo "Hola mundo ${{ github.ref }}"

 tre_job:
  needs: seconds_job
  runs-on: ubuntu-latest

  steps:
   - name: Working dir
     run : ls -la

   - name: Action
     uses: actions/checkout@v4

   - name: Working dir after action
     run : ls -la