name: Deploy to server

on: push

jobs:
 first_job:
  runs-on: ubuntu-latest

  steps:
   - name: Hola mundo
     run : echo "Hola mundo first"
     run : cat hello.php
 
 seconds_job:
  if: false
  needs: first_job
  runs-on: ubuntu-latest

  steps:
   - name: Hola mundo
     run : echo "Hola mundo seconds"