name: Deploy to server

on: push

jobs:
 first_job:
  runs-on: ubuntu-latest

  env:
   NAME: PedroGuaillas

  steps:
   - name: Hola mundo
     run : echo "Hola mundo $NAME"
 
 seconds_job:
  if: ${{ github.ref == 'refs/heads/main' }}
  needs: first_job
  runs-on: ubuntu-latest

  steps:
   - name: Hola mundo
     run : echo "Hola mundo ${{ github.ref }}"